# Generated by Django 4.2.11 on 2026-04-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locaSim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
