# Generated by Django 4.2.11 on 2026-04-05 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locaSim', '0002_appuser_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loop', models.BooleanField(default=False)),
                ('speed_kmh', models.FloatField(default=18.0)),
                ('interval_s', models.FloatField(default=0.5)),
                ('pause_s', models.FloatField(default=0.0)),
                ('from_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to='locaSim.appuser')),
            ],
            options={
                'db_table': 'saved_routes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedRouteWaypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('text', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='locaSim.savedroute')),
            ],
            options={
                'db_table': 'saved_route_waypoints',
                'ordering': ['order_index'],
                'unique_together': {('saved_route', 'order_index')},
            },
        ),
    ]
